# Generated by Django 3.2 on 2024-01-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkinsJob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jkbase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='jkbuildjob',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='jkjob',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='jkjob',
            name='jobname',
            field=models.CharField(max_length=50, verbose_name='jenkins名字'),
        ),
    ]
