# Generated by Django 3.2 on 2023-11-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='账号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('webport', models.IntegerField(verbose_name='web端口')),
                ('appID', models.IntegerField(verbose_name='appid')),
                ('appSecret', models.CharField(max_length=255, verbose_name='APPSecret')),
                ('sxtZS', models.IntegerField(verbose_name='摄像头总数')),
                ('sxtQYS', models.IntegerField(verbose_name='摄像头启用数')),
                ('sxtZXS', models.IntegerField(verbose_name='摄像头在线数')),
                ('description', models.TextField(verbose_name='描述')),
            ],
            options={
                'db_table': 'lmt',
            },
        ),
    ]
