# Generated by Django 3.2 on 2023-11-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmt',
            name='appID',
            field=models.IntegerField(blank=True, null=True, verbose_name='appid'),
        ),
        migrations.AlterField(
            model_name='lmt',
            name='appSecret',
            field=models.CharField(blank=True, max_length=255, verbose_name='APPSecret'),
        ),
        migrations.AlterField(
            model_name='lmt',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='lmt',
            name='sxtQYS',
            field=models.IntegerField(blank=True, null=True, verbose_name='摄像头启用数'),
        ),
        migrations.AlterField(
            model_name='lmt',
            name='sxtZS',
            field=models.IntegerField(blank=True, null=True, verbose_name='摄像头总数'),
        ),
        migrations.AlterField(
            model_name='lmt',
            name='sxtZXS',
            field=models.IntegerField(blank=True, null=True, verbose_name='摄像头在线数'),
        ),
        migrations.AlterField(
            model_name='lmt',
            name='webport',
            field=models.IntegerField(blank=True, null=True, verbose_name='web端口'),
        ),
    ]
