# Generated by Django 3.2 on 2023-11-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmt', '0002_auto_20231124_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmt',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
