# Generated by Django 3.2 on 2023-12-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmt', '0003_alter_lmt_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmt',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
