version: '2.2'
services:
  webapp:
    build: flaskProject/.

    ports:
      - "8080:8080"
    depends_on:
      - "db"

  db:
    image: daocloud.io/library/mysql:5.7.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=lhapp
